language: python
python:
  - "3.6"

install: pip install -r requirements.txt

before_script:
  - psql -c 'create database test_examtt;' -U postgres
  - python -m tests.setup_test_db
  - pip install html-testRunner

script: python -m tests.runner