"""empty message

Revision ID: 594c042c460d
Revises: 76f5b2fea9f9
Create Date: 2019-04-24 13:34:44.992119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594c042c460d'
down_revision = '76f5b2fea9f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentExam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentName', sa.String(), nullable=False),
    sa.Column('examId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['examId'], ['exam.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studentName'], ['student.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('studentModule')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentModule',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"studentModule_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('studentName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('moduleCode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['moduleCode'], ['module.code'], name='studentModule_moduleCode_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studentName'], ['student.name'], name='studentModule_studentName_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='studentModule_pkey')
    )
    op.drop_table('studentExam')
    # ### end Alembic commands ###
