"""empty message

Revision ID: 76f5b2fea9f9
Revises: 
Create Date: 2019-04-21 19:49:28.471151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f5b2fea9f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date',
    sa.Column('date', sa.String(length=2), nullable=False),
    sa.Column('month', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('date', 'month')
    )
    op.create_table('lifegroup',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('meeting_point',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('module',
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('time',
    sa.Column('hour', sa.String(length=2), nullable=False),
    sa.Column('minute', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('hour', 'minute')
    )
    op.create_table('warrior',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('date_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dateDate', sa.String(length=2), nullable=False),
    sa.Column('dateMonth', sa.String(length=3), nullable=False),
    sa.Column('timeHour', sa.String(length=2), nullable=False),
    sa.Column('timeMinute', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['dateDate', 'dateMonth'], ['date.date', 'date.month'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeHour', 'timeMinute'], ['time.hour', 'time.minute'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('meetingPointName', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['meetingPointName'], ['meeting_point.name'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('student',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lifegroup', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['lifegroup'], ['lifegroup.name'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('prayer_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locationName', sa.String(), nullable=False),
    sa.Column('dateTimeId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dateTimeId'], ['date_time.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['locationName'], ['location.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('studentModule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentName', sa.String(), nullable=False),
    sa.Column('moduleCode', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['moduleCode'], ['module.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studentName'], ['student.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moduleCode', sa.String(), nullable=False),
    sa.Column('prayerSlotId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['moduleCode'], ['module.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prayerSlotId'], ['prayer_slot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('moduleCode')
    )
    op.create_table('prayer_slot_warrior',
    sa.Column('prayerSlotId', sa.Integer(), nullable=False),
    sa.Column('warriorName', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['prayerSlotId'], ['prayer_slot.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warriorName'], ['warrior.name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prayerSlotId', 'warriorName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prayer_slot_warrior')
    op.drop_table('exam')
    op.drop_table('studentModule')
    op.drop_table('prayer_slot')
    op.drop_table('student')
    op.drop_table('location')
    op.drop_table('date_time')
    op.drop_table('warrior')
    op.drop_table('time')
    op.drop_table('module')
    op.drop_table('meeting_point')
    op.drop_table('lifegroup')
    op.drop_table('date')
    # ### end Alembic commands ###
