"""empty message

Revision ID: 7981a0484f14
Revises: 594c042c460d
Create Date: 2019-04-24 13:45:53.765987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7981a0484f14'
down_revision = '594c042c460d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exam_moduleCode_key', 'exam', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('exam_moduleCode_key', 'exam', ['moduleCode'])
    # ### end Alembic commands ###
