"""empty message

Revision ID: 9fa28f93e2df
Revises: ff8ad6d0436a
Create Date: 2019-04-20 12:43:13.447535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa28f93e2df'
down_revision = 'ff8ad6d0436a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prayer_slot_warrior', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prayer_slot_warrior', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
