"""empty message

Revision ID: a41640841087
Revises: 990d48d005e1
Create Date: 2019-04-18 15:40:27.003705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41640841087'
down_revision = '990d48d005e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam', sa.Column('prayerSlotId', sa.INTEGER(), nullable=False))
    op.drop_constraint('exam_locationName_fkey', 'exam', type_='foreignkey')
    op.drop_constraint('exam_dateTimeId_fkey', 'exam', type_='foreignkey')
    op.create_foreign_key(None, 'exam', 'prayer_slot', ['prayerSlotId'], ['id'], ondelete='CASCADE')
    op.drop_column('exam', 'dateTimeId')
    op.drop_column('exam', 'locationName')
    op.add_column('prayer_slot', sa.Column('locationName', sa.String(), nullable=False))
    op.drop_constraint('prayer_slot_meetingPointName_fkey', 'prayer_slot', type_='foreignkey')
    op.create_foreign_key(None, 'prayer_slot', 'location', ['locationName'], ['name'], ondelete='CASCADE')
    op.drop_column('prayer_slot', 'meetingPointName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prayer_slot', sa.Column('meetingPointName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'prayer_slot', type_='foreignkey')
    op.create_foreign_key('prayer_slot_meetingPointName_fkey', 'prayer_slot', 'meeting_point', ['meetingPointName'], ['name'], ondelete='CASCADE')
    op.drop_column('prayer_slot', 'locationName')
    op.add_column('exam', sa.Column('locationName', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('exam', sa.Column('dateTimeId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'exam', type_='foreignkey')
    op.create_foreign_key('exam_dateTimeId_fkey', 'exam', 'date_time', ['dateTimeId'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('exam_locationName_fkey', 'exam', 'location', ['locationName'], ['name'], ondelete='CASCADE')
    op.drop_column('exam', 'prayerSlotId')
    # ### end Alembic commands ###
