"""empty message

Revision ID: ff8ad6d0436a
Revises: a41640841087
Create Date: 2019-04-19 11:51:37.312096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff8ad6d0436a'
down_revision = 'a41640841087'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'exam', ['moduleCode'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exam', type_='unique')
    # ### end Alembic commands ###
